### ISSUE TITLE
Feature Request: Multiple Instances of Plugin

### ISSUE THREAD

**Issue by adamnimmo** [jneilliii/OctoPrint-WemoSwitch#12]
Howdy, I really enjoy your plugin. Would it be possible to enable the ability to control multiple wemo devices from multiple OctoPrint instances within the same Pi?

**Comment by jneilliii** [comment]
Not sure I understand, you can definitely have multiple wemos configured in the plugin and control each of them.

**Comment by adamnimmo** [comment]
Yes I see that, what I have actually done is split my OctoPrint instance 3x ways, so I have separate instances/printers controlled from the same Pi. I access my instances using port control (e.g. 192.168.1.1:5000, 192.168.1.1:5001, etc..)

When installing the plugin I think it's trying to be shared across all instances simultaneously and thus I am unable to enable it on the additional instances after the first.

Here is the guide I used in splitting my install.

https://youtu.be/7Saa1HpLRoM

**Comment by jneilliii** [comment]
I understand now. I'm not sure how that would effect enabling the plugin, but let me try on my end and see what's happening.

**Comment by jneilliii** [comment]
So I just went through the process of creating a second instance on my pi and am not seeing any issues with using the plugin in both.  I installed the plugin under one instance and then restarted the second octoprint instance to see the plugin loaded and then set the settings in it.  Maybe it's because I have the same plug configured in both instances that it's working for me maybe? Going to try removing the plug from the default instance and see if that breaks anything.

**Comment by jneilliii** [comment]
So deleting the plug settings from the default instance made no difference for me.  I'm able to use the plugin in multiple instances running from the same pi without any problems.  Check the logs and let me know if you see anything that may be related.

**Comment by adamnimmo** [comment]
Thank you for all the help, where I was breaking it was installing the plugin in both instances without restarting, somehow it was then only linking to whichever was the second install. I deleted the plugin and installed it on the primary instance, restarted and now it's working on both.

Great plugin, thanks again for the help.

**Comment by jneilliii** [comment]
Yeah, the only thing that those instructions do is to add the extra config folders and set-up the services to run on startup using the separate folders and port numbers.  The actual overall octoprint installation/server is shared between all of them so if you install a plugin on one it will install on all, you just have to restart the other instances to see the change.  There are other ways to run multiple instances which would keep the octoprint server environment to be completely duplicated, which allows for maintaining separate installs etc. but this way you used seems way easier to manage.
