### ISSUE TITLE
Changing the Icon

### ISSUE THREAD

**Issue by jkkato** [jneilliii/OctoPrint-WemoSwitch#13]
When I try to change the Icon, just a blank space appears in place of the bolt icon. If I hover over the blank space, the plug label appears in the popup, and I can click on it.

I tried "dragon" (for my ender 3 printer), and "icon-dragon". I also tried "icon-biohazard" (just picked a name from the list at random). When I switch back to "icon-bolt", that works. These are all names from the linked "Cheatsheet | Font Awsome" page linked.

**Comment by jneilliii** [comment]
Looks like the link got broken, it should be any of the following if I remember correctly. 

https://fontawesome.com/v3.2.1/icons/

**Comment by jkkato** [comment]
That worked, Thanks.

Too bad there is no Dragon in the list. That would have matched the emblem of the printer.

**Comment by jneilliii** [comment]
If you install my tab order plugin it uses the newest fontawesome icon set, but there are a couple of internal buttons that may get effected. The format is slightly different but may work.
