### ISSUE TITLE
[Request] Power off switch after print is done and temperatures hit a threshold

### ISSUE THREAD

**Issue by aidenmitchell** [jneilliii/OctoPrint-WemoSwitch#21]
It would be great if after a print is successfully completed, the plugin waits until the extruder and bed cools down, temperatures hit a threshold, such as 40 degrees for the extruder and 35 for the bed, and then shuts off the switch. It would help with power consumption and idle fan noise when the printer is idle after completing a print.

**Comment by jneilliii** [comment]
You can achieve this using gcode triggers and setting a delay. It's not the exact scenario you describe, but does resolve the power consumption concern.

**Comment by aidenmitchell** [comment]
Ok, thanks.
