### ISSUE TITLE
M81 command not working after job completion

### ISSUE THREAD

**Issue by anquinn** [jneilliii/OctoPrint-WemoSwitch#25]
The Wemo switch is not turning off after a job is completed.

The button in the navbar works when clicked to turn on/off the switch. Sending M81 followed by the IP address in the terminal works.

Adding M81 followed by the IP address "M81 192.168.1.129" to the "After print job completes" setting in Octoprint does not turn off the device.

Wemo settings:
![Screen Shot 2020-01-09 at 4 38 42 PM](https://user-images.githubusercontent.com/2035962/72107124-b51ed480-32fe-11ea-9ec5-ab49d9219c3a.png)

**Comment by jneilliii** [comment]
Try increasing the gcode off delay to something over 1 second.

**Comment by anquinn** [comment]
Thats was fast. Just running a print now to test. Will report back.

**Comment by anquinn** [comment]
60 second delay seems to have done it. Thanks!
