### ISSUE TITLE
Not connecting to Wemo Mini

### ISSUE THREAD

**Issue by mwstevenson** [jneilliii/OctoPrint-WemoSwitch#4]
Everything seems to be connected and configured properly, but the WemoSwitch addon doesn't appear to be communicating with my Wemo Mini:

![image](https://user-images.githubusercontent.com/9112504/46052899-56841600-c10e-11e8-976d-a4677f9777cc.png)

![image](https://user-images.githubusercontent.com/9112504/46052919-6c91d680-c10e-11e8-99f3-7a88f8c75c61.png)

![image](https://user-images.githubusercontent.com/9112504/46052959-a8c53700-c10e-11e8-8b0b-557c5275d588.png)

I've tried different device names, but the results are the same.

**Comment by jneilliii** [comment]
can you please enable debug logging and restart octoprint.  When the site comes back online it should attempt to discover all the wemo devices on your network and specifically try to find the one configured in settings. It will probably error out, but I need to see what's in your plugin_wemoswitch_debug.log to see what's happening.

**Comment by mwstevenson** [comment]
....and restarting OctoPrint seems to have resolved the problem!
