### ISSUE TITLE
Integrate Plugin to Octodash (Power Button)

### ISSUE THREAD

**Issue by schwos** [jneilliii/OctoPrint-WemoSwitch#47]
Didn't see a feature request tab; if I missed I apologies; but the ask is to be able to have this OctoPrint-WemoSwitch plugin enable for OctoDash support. and have it present a power button on the Octoprint screen. This way the OctoPrint System can remain on and idle and when one wants to print they can walk up and hit the power button on screen and it will switch power onto the printer that it is support.

**Comment by jneilliii** [comment]
All the inner workings are there for this to be integrated by OctoDash, as it uses a similar API to PSUControl. But it's something that UnchartedBull would have to integrate on his side. The relevant API posts would just need to include an ip as a parameter with the command parameter `turnOn` and `turnOff`. It's basically the same as I have documented with Tasmota, but without the `idx` parameter.

https://github.com/jneilliii/OctoPrint-WemoSwitch/blob/7291df6da94bd93ba94b39fce26e0b3457020bec/octoprint_wemoswitch/__init__.py#L308-L310
