### ISSUE TITLE
no issues

### ISSUE THREAD

**Issue by Vansmak** [jneilliii/OctoPrint-WemoSwitch#52]
sorry for leaving this here but i didn't know another way. this plugin works flawlessly for me. yet untekatwd to octoprint i cant get wemo mini plugs to work via homeassistant and hubitat existing integrations, i wish you could make a third party integration for those platforms as well. that is all

**Comment by jneilliii** [comment]
I thought HA has its own wemo integrations already. Unfortunately, most of my spare time is consumed with OctoPrint plugin dev/support so don't really have the time to get into another ecosystem. 

https://www.home-assistant.io/integrations/wemo

**Comment by Vansmak** [comment]
it doesn't work on the outlets. it's not reliable.
