### ISSUE TITLE
Bug when Octoprint is booted

### ISSUE THREAD

**Issue by jefflorenzini** [jneilliii/OctoPrint-WemoSwitch#54]
I'll turn on my raspberry pi to boot Octoprint, and once it's all started up, the Wemo Switch code immediately wants to turn off the plug because it's been more than the idle time out since Octoprint was last running.

Can you check when Octoprint was started, and if it's been less than the idle timeout, reset the idle timeout so it doesn't immediately try and turn off the printer?

**Comment by jneilliii** [comment]
That's something that I think I've fixed in my other power plugins. Seems to have something to do with the pi's time clock not being super accurate or something. I can definitely add the same logic to this plugin.

**Comment by jneilliii** [comment]
Added in the above commit and available in version 0.1.11rc1. If you want to test it out switch the plugin's release channel in OctoPrint's Software Update settings to `Release Candidate` and upgrade when prompted.

**Comment by jefflorenzini** [comment]
That was amazingly fast. I'll try it out, thanks!
