### ISSUE TITLE
Feature Request - PSU Control

### ISSUE THREAD

**Issue by jimmysdiy** [jneilliii/OctoPrint-WemoSwitch#56]
Hi, I use this plugin on my Octopi on the daily basis. I'd love it if you can get this to talk w/ PSU Control. I have tried your PSU Control one it is very basic. I love the added features in this plugin such as thermal runway and etc.

**Comment by jneilliii** [comment]
As stated on the other issue you posted on the PSU Control sub-plugin, the power logic is controlled by the parent plugin, not the additional one. I'm sorry this plugin has less support than PSU Control, but maybe requesting the support in the other apps would be appropriate. I'd be happy to provide any necessary information or changes required for that integration.
