### ISSUE TITLE
Auto-shutdown when OctoPrint is paused?

### ISSUE THREAD

**Issue by TrumpetH4X** [jneilliii/OctoPrint-WemoSwitch#62]
Hi there! Somewhat new to GitHub, so I hope this is the right place for this question.

Say I have a filament sensor attached to my printer that pauses my Octoprint instance. If my filament sensor triggers and my printer is sitting in this "paused" state, will this count as being "idle" and auto-shutdown my printer's Wemo switch?

Thanks for your help!

**Comment by jneilliii** [comment]
I don't think it will, but would have to go back to my code and review to verify for sure. Is this something that has happened to you with the plugin installed?

**Comment by TrumpetH4X** [comment]
Hasn’t happened to me personally (only bought the filament sensor recently), but I’ve always been worried about a print triggering/pausing and the Wemo switch turning off (e.g. say I want to swap filament colors or something and forget about the print for a few hours).  Sounds like I need to set up a test for this scenario with a really short piece of filament to see what happens. I’ll let you know! 👍
