### ISSUE TITLE
Wemo switch often reported as on while it's off, requires toggling off/on in UI to get on again

### ISSUE THREAD

**Issue by epheterson** [jneilliii/OctoPrint-WemoSwitch#64]
Sometimes I go to print and I see the bolt is green while the switch is actually off. No amount of waiting updates it to the correct state, I have to toggle it off in the UI, then back on, and it always turns on fine.

Any idea what could be causing this issue or how to fix it? I've tried decreasing the polling interval but saw no change.

Edit: Just enabled debug logging if you want me to share that to help figure out what's going wrong.

**Comment by jneilliii** [comment]
hard to say. if you enable debug logging in the plugin settings and restart OctoPrint it might help us see what's happening, or at least what the plugin is doing. Polling status should definitely be handling this state change from outside the plugin.

**Comment by epheterson** [comment]
I just noticed it's in this state. I went to print something earlier today and it correctly showed as red/off while it was off. I then tried rebooting Octoprint, and still it correctly showed as red/off. 

After the print completed, it shows in the logs that it turned the switch off, and it is indeed off, though the bolt is currently green/on. In this state, reloading the web UI and relaunching OctoPrint shows "Waiting..." then puts the green bolt there, so something isn't reading properly.

See debug logs –
[plugin_wemoswitch_debug-2.log](https://github.com/jneilliii/OctoPrint-WemoSwitch/files/9246319/plugin_wemoswitch_debug-2.log)

**Comment by epheterson** [comment]
Can you find anything useful in the logs? Anything else I can try? It’d be nice if the “Turn Off” pop-up had a Turn On button (maybe even optionally) since when we eventually send an On command, that does work.

**Comment by jneilliii** [comment]
Sorry, I've been busy with other stuff and haven't had a chance to look yet.

**Comment by jneilliii** [comment]
So I got a chance to look at the log and there doesn't seem to be anything out of the ordinary. What it sounds like is the state in the UI is getting out of sync with the server side knowledge of the device's current state. Do you happen to show any errors in the browser's developer tools (press F12 on your keyboard) on the console tab on page load when it is like this?

**Comment by epheterson** [comment]
There are several:
```
[Error] Failed to load resource: the server responded with a status of 404 () (https://domain.com/plugin/wemoswitch/static/webfonts/fa-solid-900.woff2, line 0)
[Error] WebSocket connection to 'wss://domain.com/sockjs/475/pmm5pcgb/websocket' failed: There was a bad response from the server.
[Error] Failed to load resource: the server responded with a status of 404 () (https://domain.com/plugin/wemoswitch/static/webfonts/fa-regular-400.woff2, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (https://domain.com/plugin/wemoswitch/static/webfonts/fa-brands-400.woff2, line 0)
[Error] Failed to load resource: The network connection was lost. (https://domain.com/sockjs/475/2qrowxh2/xhr_streaming?t=1660873270407, line 0)
[Error] WebSocket connection to 'wss://domain.com/sockjs/813/i1lk2ntp/websocket' failed: There was a bad response from the server.
```

**Comment by jneilliii** [comment]
the 404 ones I've seen before for fontawesome webfont download, but that shouldn't impact the plugin. the websocket one is strange, can't say I've seen that before and might be part of a chrome extension possibly.

**Comment by epheterson** [comment]
I enabled Web Sockets on my reverse proxy and that improved the behavior of Octoprint overall (as well as many other self hosted apps) and seems to have made this issue disappear too. So, closing and thanks!
