### ISSUE TITLE
Raspberry Pi crashing when installing

### ISSUE THREAD

**Issue by Bentheminernz** [jneilliii/OctoPrint-WemoSwitch#75]
Hello,

I was installing Octoprint Wemo and it got up to the step "Building wheel for lxml (pyproject.toml): started" it says that for ages and then eventually it seems my raspberry pi crashes, I can't SSH into it or access OctoPrint website. I'm using a Raspberry Pi Zero 2w and OctoPrint is up to date,

**Comment by jneilliii** [comment]
Haven't tried installing this one in a while, can you please provide the full plugin manager console log and OctoPrint log please.
